<?xml version="1.0" encoding="utf-8"?><Database Name="StoreDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-1N3NNJP;Initial Catalog=StoreDB;Integrated Security=True" SettingsObjectName="SemesterProject.Properties.Settings" SettingsPropertyName="StoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="CUSTOMER_PURCHASE" Member="PURCHASEs" ThisKey="CustomerId" OtherKey="CustomerId" Type="PURCHASE" />
    </Type>
  </Table>
  <Table Name="dbo.STORE_ITEM" Member="STORE_ITEMs">
    <Type Name="STORE_ITEM">
      <Column Name="StoreItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="QuantityAvailable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="STORE_ITEM_PURCHASE_STORE_ITEM" Member="PURCHASE_STORE_ITEMs" ThisKey="StoreItemId" OtherKey="StoreItemId" Type="PURCHASE_STORE_ITEM" />
    </Type>
  </Table>
  <Table Name="dbo.PURCHASE" Member="PURCHASEs">
    <Type Name="PURCHASE" Id="ID1">
      <Column Name="PurchaseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseDateTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="PURCHASE_PURCHASE_STORE_ITEM" Member="PURCHASE_STORE_ITEMs" ThisKey="PurchaseId" OtherKey="PurchaseId" Type="PURCHASE_STORE_ITEM" />
      <Association Name="CUSTOMER_PURCHASE" Member="CUSTOMER" ThisKey="CustomerId" OtherKey="CustomerId" Type="CUSTOMER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PURCHASE_STORE_ITEM" Member="PURCHASE_STORE_ITEMs">
    <Type Name="PURCHASE_STORE_ITEM">
      <Column Name="PurchaseId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StoreItemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="PURCHASE_PURCHASE_STORE_ITEM" Member="PURCHASE" ThisKey="PurchaseId" OtherKey="PurchaseId" Type="PURCHASE" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="STORE_ITEM_PURCHASE_STORE_ITEM" Member="STORE_ITEM" ThisKey="StoreItemId" OtherKey="StoreItemId" Type="STORE_ITEM" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.CREATE_NEW_PURCHASE" Method="CREATE_NEW_PURCHASE">
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PurchasedStoreItems" Parameter="purchasedStoreItems" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>